require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

# 以下を追加
Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 15

Style/BlockDelimiters:
  Enabled: false

Layout/LineLength:
  Max: 300

RSpec/ExampleLength:
  Max: 20
